FROM alpine:3.16 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.16
EXPOSE 3000

ENV GODEBUG netdns=go
ENV DRONE_PLATFORM_OS linux
ENV DRONE_PLATFORM_ARCH amd64

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ADD release/linux/amd64/drone-runner-podman /bin/
ENTRYPOINT ["/bin/drone-runner-podman"]
